"""worg_request 삭제, schedule_conditions 테이블 추가

Revision ID: 00d77c9685a1
Revises: 8cf1f212ca91
Create Date: 2026-03-10 14:36:14.425998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00d77c9685a1'
down_revision: Union[str, Sequence[str], None] = '8cf1f212ca91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=20), nullable=False),
    sa.Column('fixed_conditions', sa.String(), nullable=False),
    sa.Column('use_at', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('create_dt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.String(length=20), nullable=True),
    sa.Column('updated_by_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_conditions_id'), 'schedule_conditions', ['id'], unique=False)
    op.drop_index(op.f('ix_work_requests_id'), table_name='work_requests')
    op.drop_table('work_requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userid', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('create_dt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('update_dt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('updated_by_id', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], name=op.f('work_requests_userid_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('work_requests_pkey'))
    )
    op.create_index(op.f('ix_work_requests_id'), 'work_requests', ['id'], unique=False)
    op.drop_index(op.f('ix_schedule_conditions_id'), table_name='schedule_conditions')
    op.drop_table('schedule_conditions')
    # ### end Alembic commands ###
