"""users 테이블 relationship 추가 수정

Revision ID: 0a67caef2bc1
Revises: 8b9a24d33e13
Create Date: 2026-03-10 16:56:41.855768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a67caef2bc1'
down_revision: Union[str, Sequence[str], None] = '8b9a24d33e13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
