"""전체적인 수정을 위한 스키마 삭제 후 테이블 재구성

Revision ID: 1632a68e2955
Revises: 
Create Date: 2026-02-25 16:14:10.642130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1632a68e2955'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('create_dt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.String(length=20), nullable=True),
    sa.Column('updated_by_id', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('role_code')
    )
    op.create_index(op.f('ix_roles_role_code'), 'roles', ['role_code'], unique=False)
    op.create_table('users',
    sa.Column('userid', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('service_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_login_check', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('create_dt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.String(length=20), nullable=True),
    sa.Column('updated_by_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['role_code'], ['roles.role_code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_index(op.f('ix_users_userid'), 'users', ['userid'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('create_dt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.String(length=20), nullable=True),
    sa.Column('updated_by_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.userid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_table('login_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('login_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('create_dt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.String(length=20), nullable=True),
    sa.Column('updated_by_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_histories_id'), 'login_histories', ['id'], unique=False)
    op.create_table('shift_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('create_dt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.String(length=20), nullable=True),
    sa.Column('updated_by_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.userid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_types_id'), 'shift_types', ['id'], unique=False)
    op.create_table('work_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('create_dt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.String(length=20), nullable=True),
    sa.Column('updated_by_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_requests_id'), 'work_requests', ['id'], unique=False)
    op.create_table('work_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('shift_type_id', sa.Integer(), nullable=False),
    sa.Column('create_dt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.String(length=20), nullable=True),
    sa.Column('updated_by_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_type_id'], ['shift_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'employee_id', name='uq_work_schedule_date_employee')
    )
    op.create_index(op.f('ix_work_schedules_id'), 'work_schedules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_schedules_id'), table_name='work_schedules')
    op.drop_table('work_schedules')
    op.drop_index(op.f('ix_work_requests_id'), table_name='work_requests')
    op.drop_table('work_requests')
    op.drop_index(op.f('ix_shift_types_id'), table_name='shift_types')
    op.drop_table('shift_types')
    op.drop_index(op.f('ix_login_histories_id'), table_name='login_histories')
    op.drop_table('login_histories')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_userid'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_role_code'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
